tasks:
  - name: terraform-cli
    env:
      TF_LOG: DEBUG
    before: |
      cd $GITPOD_REPO_ROOT
      cp $GITPOD_REPO_ROOT/terraform.tfvars.example $GITPOD_REPO_ROOT/terraform.tfvars
      source ./bin/create_bash_aliases
      source ./bin/install_terraform_cli
      source ./bin/generate_tfrc_credentials
      gp sync-done terraform-cli
  - name: azure-cli
    before: |
      cd $GITPOD_REPO_ROOT
      source ./bin/create_bash_aliases
      gp sync-await terraform-cli && source ./bin/install_azure_cli
vscode:
  extensions:
    - hashicorp.terraform
    - ms-vscode.azurecli
